version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

    cooldown:
      default-days: 7
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    groups:
      commitlint:
        patterns:
          - "@commitlint/*"
      mantine:
        patterns:
          - "@mantine*"
      storybook:
        patterns:
          - "*storybook*"
      dev-dependencies: # all other dev dependencies
        dependency-type: "development"
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
