version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    groups:
      storybook:
        patterns:
          - "*storybook*"
      vite:
        patterns:
          - "*vite*"
      mantine:
        patterns:
          - "@mantine*"
      radix:
        patterns:
          - "@radix-ui/*"
