version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

    cooldown:
      default-days: 7
      exclude:
        - github.com/einride/*
        - github.com/einride-autonomous/*
        - github.com/einride-labs/*
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    groups:
      commitlint:
        patterns:
          - "@commitlint/*"
        update-types:
          - "minor"
          - "patch"
      mantine:
        patterns:
          - "@mantine*"
        update-types:
          - "minor"
          - "patch"
      storybook:
        patterns:
          - "*storybook*"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies: # all other dev dependencies
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
      exclude:
        - github.com/einride/*
        - github.com/einride-autonomous/*
        - github.com/einride-labs/*
