apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: einride-ui
  title: Einride UI
  description: Core components that adhere to Einride's design system.
  annotations:
    backstage.io/source-location: url:https://github.com/einride/einride-ui/tree/main
    github.com/project-slug: einride/ui
    github.com/team-slug: einride/platform-engineering
spec:
  type: library
  system: einride-ui
  owner: platform-engineering
  lifecycle: production
