name: CI

on:
  push:
    branches:
      - master

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12

      - name: Make
        run: make

      - name: Upload lib artifact
        uses: actions/upload-artifact@v2
        with:
          name: lib
          path: lib

  release:
    needs: make
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12

      - name: Download lib arcitact
        uses: actions/download-artifact@v2
        with:
          name: lib

      - name: Run semantic-release
        run: make semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
